### PR TITLE
Update contributor list

### PR DESCRIPTION
**Pull request by jamesgeorge007**
related #100 
Update the list within Readme.md

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
cc @HcySunYang

**Comment by jamesgeorge007** [comment]
@HcySunYang would be great if you could give it a try on [teachcode](http://github.com/madlabsinc/teachcode). Also, consider leaving a :star:

**Comment by jamesgeorge007** [comment]
Also, I would love to collaborate with, would you mind adding me to the org?

**Comment by HcySunYang** [comment]
Of course, thank you for all your work. 😉

**Pull request merged**
